USE [Priebslogistik];
-- einzeln, wie gewünscht
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name='IX_BEWEGUNG_BuchDT_Vorgang')
  CREATE INDEX IX_BEWEGUNG_BuchDT_Vorgang     ON dbo.BEWEGUNG (BUCHUNGDATUMZEITVORGANG);

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name='IX_BEWEGUNG_BuchDT_Ziel')
  CREATE INDEX IX_BEWEGUNG_BuchDT_Ziel        ON dbo.BEWEGUNG (BUCHUNGDATUMZEITZIELSERVER);

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name='IX_BEWEGUNG_BuchZeitVorgang')
  CREATE INDEX IX_BEWEGUNG_BuchZeitVorgang    ON dbo.BEWEGUNG (BUCHUNGZEITVORGANG);
