CREATE OR ALTER TRIGGER dbo.trg_BEWEGUNG_SetDateStrings
ON dbo.BEWEGUNG
AFTER INSERT, UPDATE
AS
BEGIN
  SET NOCOUNT ON;
  UPDATE b
  SET
    BUCHUNGDATUMVORGANG    = CASE WHEN b.BUCHUNGDATUMZEITVORGANG    IS NULL THEN NULL ELSE CONVERT(nchar(8), b.BUCHUNGDATUMZEITVORGANG,    112) END,
    BUCHUNGZEITVORGANG     = CASE WHEN b.BUCHUNGDATUMZEITVORGANG    IS NULL THEN NULL ELSE REPLACE(CONVERT(nchar(8), b.BUCHUNGDATUMZEITVORGANG,    108),':','') END,
    BUCHUNGDATUMZIELSERVER = CASE WHEN b.BUCHUNGDATUMZEITZIELSERVER IS NULL THEN NULL ELSE CONVERT(nchar(8), b.BUCHUNGDATUMZEITZIELSERVER, 112) END,
    BUCHUNGZEITZIELSERVER  = CASE WHEN b.BUCHUNGDATUMZEITZIELSERVER IS NULL THEN NULL ELSE REPLACE(CONVERT(nchar(8), b.BUCHUNGDATUMZEITZIELSERVER, 108),':','') END
  FROM dbo.BEWEGUNG b
  JOIN inserted i ON i.IDNR = b.IDNR;
END;
GO
